### ISSUE TITLE
Impound infinite cars

### ISSUE THREAD

**Issue by rico956** [arnevdaele/esx_simplegarages#1]
There is an issue with the impound where you can spawn as many cars as you want out of the impound

**Comment by rico956** [comment]
Fixed:

--client.lua - replace openImpoundMenu to stop infinite spawn
openImpoundMenu = function()
    local elements = {}

    ESX.TriggerServerCallback("esx_simplegarages:callback:GetImpoundedVehicles", function(ImpoundedVehicles)
        for k, v in pairs(ImpoundedVehicles) do
            local aheadVehName = GetDisplayNameFromVehicleModel(v.vehicle.model)
            local vehicleName = GetLabelText(aheadVehName)
            local labelvehicle
            local labelvehicle = ('%s (%s) - <span style="color:#27ae60">€%s</span>'):format(vehicleName, v.plate, v.price)

            table.insert(elements, {label = labelvehicle, value = v})
        end

        ESX.UI.Menu.Open('default', GetCurrentResourceName(), 'spawn_owned_car', {
			title = 'Apreendidos - Cidade',
			align = left,
			elements = elements
		}, function(data, menu)
            menu.close()
			-- Check if the plate exists in the spanwed cars. This to avoid infinite spawn. 
			local gameVehicles = ESX.Game.GetVehicles()
			for i = 1, #gameVehicles do
				local vehicle = gameVehicles[i]
				if DoesEntityExist(vehicle) then
					if Config.Trim(GetVehicleNumberPlateText(vehicle)) == Config.Trim(data.current.value.plate) then
						exports['mythic_notify']:SendAlert('error', ('Este carro não se encontra apreendido.'))
						--ESX.ShowNotification("Este carro ainda está pela cidade")
					return
					end
				end
			end
			
            ESX.TriggerServerCallback("esx_simplegarages:callback:GetPlayerCashAmount", function(amount)
                if amount >= data.current.value.price then
                    TriggerServerEvent("esx_simplegarages:server:PayImpoundBill", data.current.value.price)
                    spawnVehicle(data.current.value.vehicle, data.current.value.fuel, data.current.value.engine, data.current.value.plate)
                else
                    menu.close()
                    --ESX.ShowNotification("You don't have enough cash money to pay the bill...")
					exports['mythic_notify']:SendAlert('error', ('Não tem dinheiro suficiente!'))
                end
            end)
		end, function(data, menu)
			menu.close()
		end)
    end)
end

--config.lua add function to trim

Config.Trim = function(value)
    if value then
        return (string.gsub(value, "^%s*(.-)%s*$", "%1"))
    else
        return nil
    end

**Comment by rico956** [comment]
Fixed: 

`--client.lua - replace openImpoundMenu to stop infinite spawn
openImpoundMenu = function()
    local elements = {}

    ESX.TriggerServerCallback("esx_simplegarages:callback:GetImpoundedVehicles", function(ImpoundedVehicles)
        for k, v in pairs(ImpoundedVehicles) do
            local aheadVehName = GetDisplayNameFromVehicleModel(v.vehicle.model)
            local vehicleName = GetLabelText(aheadVehName)
            local labelvehicle
            local labelvehicle = ('%s (%s) - <span style="color:#27ae60">€%s</span>'):format(vehicleName, v.plate, v.price)

            table.insert(elements, {label = labelvehicle, value = v})
        end

        ESX.UI.Menu.Open('default', GetCurrentResourceName(), 'spawn_owned_car', {
			title = 'Apreendidos - Cidade',
			align = left,
			elements = elements
		}, function(data, menu)
            menu.close()
			-- Check if the plate exists in the spanwed cars. This to avoid infinite spawn. 
			local gameVehicles = ESX.Game.GetVehicles()
			for i = 1, #gameVehicles do
				local vehicle = gameVehicles[i]
				if DoesEntityExist(vehicle) then
					if Config.Trim(GetVehicleNumberPlateText(vehicle)) == Config.Trim(data.current.value.plate) then
						exports['mythic_notify']:SendAlert('error', ('Este carro não se encontra apreendido.'))
						--ESX.ShowNotification("Este carro ainda está pela cidade")
					return
					end
				end
			end
			
            ESX.TriggerServerCallback("esx_simplegarages:callback:GetPlayerCashAmount", function(amount)
                if amount >= data.current.value.price then
                    TriggerServerEvent("esx_simplegarages:server:PayImpoundBill", data.current.value.price)
                    spawnVehicle(data.current.value.vehicle, data.current.value.fuel, data.current.value.engine, data.current.value.plate)
                else
                    menu.close()
                    --ESX.ShowNotification("You don't have enough cash money to pay the bill...")
					exports['mythic_notify']:SendAlert('error', ('Não tem dinheiro suficiente!'))
                end
            end)
		end, function(data, menu)
			menu.close()
		end)
    end)
end

--config.lua add function to trim

Config.Trim = function(value)
    if value then
        return (string.gsub(value, "^%s*(.-)%s*$", "%1"))
    else
        return nil
    end`

**Comment by rico956** [comment]
```
--client.lua - replace openImpoundMenu to stop infinite spawn
openImpoundMenu = function()
    local elements = {}

    ESX.TriggerServerCallback("esx_simplegarages:callback:GetImpoundedVehicles", function(ImpoundedVehicles)
        for k, v in pairs(ImpoundedVehicles) do
            local aheadVehName = GetDisplayNameFromVehicleModel(v.vehicle.model)
            local vehicleName = GetLabelText(aheadVehName)
            local labelvehicle
            local labelvehicle = ('%s (%s) - <span style="color:#27ae60">€%s</span>'):format(vehicleName, v.plate, v.price)

            table.insert(elements, {label = labelvehicle, value = v})
        end

        ESX.UI.Menu.Open('default', GetCurrentResourceName(), 'spawn_owned_car', {
			title = 'Apreendidos - Cidade',
			align = left,
			elements = elements
		}, function(data, menu)
            menu.close()
			-- Check if the plate exists in the spanwed cars. This to avoid infinite spawn. 
			local gameVehicles = ESX.Game.GetVehicles()
			for i = 1, #gameVehicles do
				local vehicle = gameVehicles[i]
				if DoesEntityExist(vehicle) then
					if Config.Trim(GetVehicleNumberPlateText(vehicle)) == Config.Trim(data.current.value.plate) then
						exports['mythic_notify']:SendAlert('error', ('Este carro não se encontra apreendido.'))
						--ESX.ShowNotification("Este carro ainda está pela cidade")
					return
					end
				end
			end
			
            ESX.TriggerServerCallback("esx_simplegarages:callback:GetPlayerCashAmount", function(amount)
                if amount >= data.current.value.price then
                    TriggerServerEvent("esx_simplegarages:server:PayImpoundBill", data.current.value.price)
                    spawnVehicle(data.current.value.vehicle, data.current.value.fuel, data.current.value.engine, data.current.value.plate)
                else
                    menu.close()
                    --ESX.ShowNotification("You don't have enough cash money to pay the bill...")
					exports['mythic_notify']:SendAlert('error', ('Não tem dinheiro suficiente!'))
                end
            end)
		end, function(data, menu)
			menu.close()
		end)
    end)
end

--config.lua add function to trim

Config.Trim = function(value)
    if value then
        return (string.gsub(value, "^%s*(.-)%s*$", "%1"))
    else
        return nil
    end
```

**Comment by arnevdaele** [comment]
Should be fixed in new release.

**Comment by yagizher** [comment]
// Fixed, can be closed.
